language: cpp

os:
    - osx
    - windows

before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then sh ./scripts/osx/install-dependencies.sh ; fi
    - if [ "$TRAVIS_OS_NAME" = "windows" ] ; then ./scripts/windows/install-dependencies.bat ; fi

install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then sh ./scripts/osx/build.sh ; fi
    - if [ "$TRAVIS_OS_NAME" = "windows" ] ; then ./scripts/windows/build.bat ; fi

script:
    - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then ./build/tests/DirectPlayHelperTest ; fi
    - if [ "$TRAVIS_OS_NAME" = "windows" ] ; then ./build/tests/Release/DirectPlayHelperTest.exe ; fi
